hello:
    pattern:  /liip/hello/{name}.{_format}
    defaults: { _controller: liip_hello.world.controller:indexAction, _format: html }

hello_fallback:
    pattern:  /liip/hello.{_format}
    defaults: { _controller: liip_hello.world.controller:indexAction, _format: html }

hello_serializer:
    pattern:  /liip/serializer.{_format}
    defaults: { _controller: liip_hello.world.controller:serializerAction, _format: json }

hello_facebook:
    pattern:  /liip/facebook
    defaults: { _controller: liip_hello.world.controller:facebookAction, _format: html }

hello_exception:
    pattern:  /liip/exception.{_format}
    defaults: { _controller: liip_hello.world.controller:exceptionAction, _format: html }

hello_validation_failure:
    pattern:  /liip/validation_failure.json
    defaults: { _controller: liip_hello.world.controller:validationFailureAction, _format: json }

hello_facebook_check:
    pattern:  /liip/facebook-check
    defaults: { _controller: liip_hello.world.controller:facebookAction, _format: html }

hello_facebook_logout:
    pattern:  /liip/facebook-logout
    defaults: { _controller: liip_hello.world.controller:facebookAction, _format: html }

hello_phpcr:
    pattern:  /liip/phpcr/{title}
    defaults: { _controller: liip_hello.phpcr.controller:indexAction, _format: html }
    requirements:
        title: .+

extra:
    resource: "@LiipHelloBundle/Controller/ExtraController.php"
    type:     annotation

rest:
    resource: liip_hello.rest.controller
    type:     rest

hello_vie_article:
    pattern:  /liip/hello/vie/{id}
    defaults: { _controller: liip_hello.vie.controller:articleAction, _format: html }

hello_hyphenator:
    pattern:  /liip/hyphenator
    defaults: { _controller: liip_hello.world.controller:hyphenatorAction, _format: html }

hello_custom_handler:
    pattern:  /liip/customHandler.{_format}
    defaults: { _controller: liip_hello.world.controller:customHandlerAction, _format: rss }

hello_tree:
    pattern:  /liip/tree
    defaults: { _controller: liip_hello.tree.controller:indexAction, _format: html }

tree:
    resource: "@SymfonyCmfPHPCRBrowserBundle/Resources/config/routing.xml"
    prefix:  /liip
